spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/postgres_test
    username: pguser01
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:      ddl-auto: create
      #updateでテーブル作成のみに変更可